name: Publish Node.js Package
on:
  release:
    types: [created]
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      id: bump_version
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: master
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://registry.npmjs.org'
    - run: |
        git config --global user.email "${{ github.actor }}@noreply.github.com"
        git config --global user.name "${{ github.actor }}"
        echo "${{ steps.bump_version.outputs.tag }}"
    - run: npm install
    # Publish to npm
    - run: npm version "${{ steps.bump_version.outputs.tag }}" && npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@soleo'
    # Publish to GitHub Packages
    - run: |
        npm login --registry=https://npm.pkg.github.com --scope=@soleo
        echo registry=https://npm.pkg.github.com/soleo >> .npmrc
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
